### PR TITLE
Recursively upload via context if file path is directory

### PR DESCRIPTION
**Pull request by tyler-richardett**
## Proposed changes

Currently, when running `dbx execute` with `--upload-via-context`, if any task parameters point to directories rather than files (e.g., executing `pytest` against a directory of tests called `tests/integration`), `read_bytes` throws the following error: `IsADirectoryError: [Errno 21] Is a directory: 'tests/integration'`.

With this change, `upload_file` steps recursively through the directory and any child directories.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

N/A

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @tyler-richardett , 
by the security rules, all commits should be gpg signed. Please sign your commits 🙌

**Comment by tyler-richardett** [comment]
@renardeinside Done! Sorry about that.

**Comment by renardeinside** [comment]
hi @tyler-richardett , 
taking into account that this patch of code is practically impossible to test, have you done some manual testing?

**Comment by tyler-richardett** [comment]
@renardeinside Yep! I manually tested with a few different sizes and depths. All worked as expected.

**Comment by renardeinside** [comment]
Good job @tyler-richardett 
Please reflect the changes in the CHANGELOG.md and I'll merge this one.

**Comment by tyler-richardett** [comment]
@renardeinside Done. Thanks!

**Pull request merged**
