### PR TITLE
fix: Typo in permissions docs

### PR DESCRIPTION
**Pull request by dinispeixoto**
## Proposed changes

Just fixing a small typo in the Permissions documentation.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @dinispeixoto , 
your commits are not signed - please take a look at [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and sign them properly. Due to security reasons we cannot merge unsigned commits.

**Comment by dinispeixoto** [comment]
hey @renardeinside, sorry should have read the contributing guidelines first

btw just noticed that the contributing docs link is broken in the README.md, should I take the opportunity to also fix this?

**Comment by renardeinside** [comment]
yes, that would be great! :)

**Comment by dinispeixoto** [comment]
Should be good to go

**Comment by renardeinside** [comment]
thank you @dinispeixoto !

**Pull request merged**
