### PR TITLE
:sparkles: Add support for additional headers

### PR DESCRIPTION
**Pull request by bjtho08**
## Proposed changes

Closes https://github.com/databrickslabs/dbx/issues/467

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

This PR adds three modes of supplying additional headers. The two main modes use either environment variables or additional config variables added to the databrickscfg file. through the following three environment variables:
| Environment variable | databrickscfg variable | Description |
|--|--|--|
| `AZURE_SERVICE_PRINCIPAL_TOKEN` | `azure_service_principal_token` | An Azure AD token generated on behalf of a Service Principal |
| `WORKSPACE_ID` | `workspace_id` | The Azure Resource ID of the target workspace |
| `ORG_ID` | `org_id` | The Databricks workspace ID of the target workspace |

By setting these variables, each `dbx` command execution will provide the following three headers to the `ApiClient` in addition to the predefined headers (i.e. `Authorization, Content-Type, User-Agent`):
- `X-Databricks-Azure-SP-Management-Token`
- `X-Databricks-Azure-Workspace-Resource-Id`
- `X-Databricks-Org-Id`

The addition of these additional headers will allow a Service Principal access to a Databricks workspace without being a registered user of said workspace (though it is still necessary for the SP to be at least a `Contributor` in the Azure Resource). This allows companies to improve the security around their automation without upgrading their Databricks subscription to the Premium tier.

As I mentioned, there are three modes of supplying additional headers. The last mode is through adding the `--header/-H key1=val1` option to the `dbx` commands. Like the `--tag` option for `dbx deploy`, this option can (and should) be repeated multiple times to add several headers.

I have not updated the documentation as I wouldn't know where to put this feature. I did update the CLI help messages to reflect the new options available for each of the commands.

### CODE REVIEW

**Comment by bjtho08** [comment]
@renardeinside I don't know if you received notification about this PR, but I can't run the test-pipeline without approval from you or another maintainer 👋

**Comment by bjtho08** [comment]
@renardeinside can we try running the test-pipeline again? It should work now.

**Comment by renardeinside** [comment]
hi @bjtho08 , 
all commits should be signed, this is a strict security rule we enforce on all repos. 
Please sign your commits so I can merge the PR.

**Comment by bjtho08** [comment]
@renardeinside I will make another commit soon which will be GPG signed. My dev environment is acting up at the moment.

**Comment by bjtho08** [comment]
@renardeinside How can I sign the previous commits that are not verified? Should I rebase my branch or squash the commits?

**Comment by renardeinside** [comment]
Hi @bjtho08 , 
> Should I rebase my branch or squash the commits?
I don't remember tbh, I think this is one of the working [instructions](https://www.manthanhd.com/2021/06/18/how-to-retroactively-sign-all-commits-in-a-branch/) (it's based on rebase).

**Comment by bjtho08** [comment]
@renardeinside I would say this PR is ready to be merged now, assuming it passes the remaining two checks.

**Pull request merged**
