### PR TITLE
Added support for multi-task jobs.

### PR DESCRIPTION
**Pull request by jiri-vinarek**
## Proposed changes

Add support multi-task jobs: https://github.com/databrickslabs/dbx/issues/61

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by rfcortes** [comment]
Hello, 

Do you a have an estimated date to release this feature? 

Thanks

**Comment by renardeinside** [comment]
hi @rfcortes . 
0.1.6 is planned for release in mid-September. Please feel free to contribute if you would like to make the process faster.

**Comment by rfcortes** [comment]
Hello,

Does the current release 0.1.6 includes support for multi-task jobs? If not, do you still plan to release it in mid-september?

Thanks

**Comment by renardeinside** [comment]
hello @rfcortes - nope, it was moved to 0.2.0 - 0.1.6 was a hotfix release. 
Yes, the plan is still mid-September (10th/11th).

**Comment by rfcortes** [comment]
Still on track to release this weekend (10th/11th)? 
We're very excited waiting to test this feature 👍

**Comment by jiri-vinarek** [comment]
@rfcortes you can use git repository as a Python package.
You can add `-e git://github.com/jiri-vinarek/dbx.git@multi-task-jobs#egg=dbx` into your `unit-requirements.txt` file and test it this way.

**Pull request closed without merging**
