### PR TITLE
Fix documentation for JSON structure of deployment file

### PR DESCRIPTION
**Pull request by alexott**
## Proposed changes

Fix documentation for JSON structure of deployment file

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @alexott , 
please sign your commits as per this [doc](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) so I'll be able to merge them.

**Comment by alexott** [comment]
Contributing guideline doesn’t say anything about this requirement

**Comment by renardeinside** [comment]
@alexott - fair point. I've added the PR to mention this req explicitly - https://github.com/databrickslabs/dbx/pull/65

**Comment by jspreddy** [comment]
I can make these changes in my pr. I am in there anyways.

**Pull request closed without merging**
