### PR TITLE
Handle pytest exit code in entrypoint

### LINKED ISSUE #524: Job succeeds when pytest fails using cookiecutter entrypoint.py
## Expected Behavior
Databricks job to fail when pytest fails

## Current Behavior
Databricks job succeeds when pytest fails

## Steps to Reproduce (for bugs)
`tests/integration/test_foo.py`:
```python
def test_foo():
    assert 0
```

`conf/deployment.yml`:
```yaml
environments:
  default:
    workflows:
      - name: "my-integration-tests"
        tasks:
          - task_key: "main"
            <<: *basic-static-cluster
            libraries:
              - pypi:
                  package: "pytest"
            spark_python_task:
              python_file: "file://tests/entrypoint.py"
              parameters: [ "file:fuse://tests/integration" ]
```

```sh
$ dbx deploy my-integration-tests
$ dbx launch my-integration-tests
```

## Context
I believe the cookiecutter template is ignoring `pytest`'s exit code, probably just needs `sys.exit(pytest.main(...))`?

https://github.com/databrickslabs/dbx/blob/99d6126de691af24701a62fffb03d982bb9b5b9f/dbx/templates/projects/python_basic/render/%7B%7Bcookiecutter.project_name%7D%7D/tests/entrypoint.py#L6

## Your Environment

* dbx version used: 0.7.6
* Databricks Runtime version: 10.4 LTS

### PR DESCRIPTION
**Pull request by jckegelman**
## Proposed changes

> Describe the big picture of your changes here to communicate to the maintainers. If it fixes a bug or resolves a feature request, please provide a link to that issue.

Handle the `pytest` exit code in the cookiecutter `entrypoint.py` that is used for integration tests. This will cause the Databricks job to fail if any of the `pytest` tests fail. Fixes #524 . 

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

> If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

I believe this to be a relatively small change.

Tested `dbx launch` with failing test:
Screen Shot 2022-10-24 at 1 21 17 PM

Tested `dbx launch` with passing test:
Screen Shot 2022-10-24 at 1 21 29 PM

Tested `dbx execute` with failing test:
```
⠋ Running the entrypoint file[dbx][2022-10-24 12:24:41.573] Execution failed, please follow the given error
...
RuntimeError: Command execution failed. Traceback from cluster:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<command--1> in <module>
      6     exit_code = pytest.main(sys.argv[1:])
      7     if exit_code != pytest.ExitCode.OK:
----> 8         raise RuntimeError(f"pytest returned non-zero exit code: {str(exit_code)}. See logs for details.")
RuntimeError: pytest returned non-zero exit code: ExitCode.TESTS_FAILED. See logs for details.
```

Tested `dbx execute` with passing test:
```
⠏ Running the entrypoint file[dbx][2022-10-24 12:23:59.670] Command successfully executed
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
rootdir: /dbfs/Shared/dbx/projects/dbx_sample_project/748adf782ba74534b8bab4d08d82a0d2/artifacts/tests/integration
collected 1 item

../../dbfs/Shared/dbx/projects/dbx_sample_project/748adf782ba74534b8bab4d08d82a0d2/artifacts/tests/integration/e2e_test.py . [100%]
```

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @jckegelman , 
this PR LGTM, but I'm missing 2 things:
1. Please sign your commits, we don't take unsigned commits due to security reasons
2. Have you tested this behaviour in both `dbx execute` and `dbx launch` modes?

**Comment by jckegelman** [comment]
> * Please sign your commits, we don't take unsigned commits due to security reasons
Done

> * Have you tested this behaviour in both `dbx execute` and `dbx launch` modes?
Updated the exit coding handling and updated the PR description with some screen shots and console output.

**Comment by renardeinside** [comment]
Thanks a lot @jckegelman , this LGTM!
I'll accept it after big merge of #522

**Comment by renardeinside** [comment]
@jckegelman could you please describe the change in the `CHANGELOG.md`?

**Comment by jckegelman** [comment]
> @jckegelman could you please describe the change in the `CHANGELOG.md`?

Done!

**Pull request merged**
