### PR TITLE
better args parser

### PR DESCRIPTION
**Pull request by copdips**
## Proposed changes

`p.parse_known_args()[0]` should be enough instead of `p.parse_known_args(sys.argv[1:])[0]`

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Further comments

with some minor imports sorting and typo fix in the same files

### CODE REVIEW

**Comment by copdips** [comment]
@renardeinside, please review

**Comment by copdips** [comment]
@renardeinside 
please review

**Comment by copdips** [comment]
Hi @renardeinside,  thanks for your in-depth reply. 

To build a CLI application like dbx itself, I've the same thoughts as yours, `typer` is a perfect choice. 
I've never used `omegaconf` before, just took a quick overview, it seems that there's [OmegaConf.from_cli()](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#from-command-line-arguments) which looks great.

Maybe the argument parsing is a little bit out of scope of dbx which is not a deployment stuff, but if you would like to introduce new dependencies for user's databricks tasks (not dbx itself), yes, I should than close this PR.

**Comment by renardeinside** [comment]
I've discovered various options and I think we could use the [`hydra`](https://hydra.cc/docs/intro/) application framework in our Python templates - it provides various useful interfaces, looks fancy and has good documentation. Would that be something that you agree with @copdips ?

**Comment by copdips** [comment]
Sorry for the late about this thread.
After reading the doc of hydra, it looks like a good choice for config management.

What I think is how to let dbx to use hydra config, as the entrypoint is a python based file, so `dbx deploy --deployment-file` should handle python file type too, and probably also with a new argument `--deployment-file-arguments`.

Furthermore it would be nice if can we use the python deployment file in a more generalized way out of hydra, which means whatever it's hydra or not, as long as `--deployment-file` is a python file, just let dbx to run it, and the given python file should print the deployment in stdout that dbx can capture. By this way, we can fully leverage the python power to generate complex/redundant  deployment definition.

**Comment by renardeinside** [comment]
I also was thinking in the same direction - what if we allow users to build a configuration in the same way as it's done in the FastAPI for instance. 

Brief design outline:
```python
# e.g. .dbx/configurator.py
from dbx import configurator
from dbx import Workflow, Task

wf1 = Workflow(...)
wf2 = Workflow(...)

wf1.add(Task(...))
wf1.add(Task(...))

wf2.add(Task(...))

configurator.add_workflow(w1, w2)

```

And then in the dbx deploy (or launch or whatever):

```
dbx deploy --deployment-file=.dbx/configurator.py
```

**Comment by renardeinside** [comment]
i think this change requires a bigger PR and proper design phase. Please check this issue and share your thoughts - https://github.com/databrickslabs/dbx/issues/547

**Comment by renardeinside** [comment]
This one I'll close for the moment since it won't be implemented in the way it's provided.

**Pull request closed without merging**
