### PR TITLE
Add Support for Jinja2 Deployment Files

### PR DESCRIPTION
**Pull request by elenamartina**
## Proposed changes

Proposed resolution for Issue #123  [[FEATURE] Add Support for Jinja2 Deployment Files](https://github.com/databrickslabs/dbx/issues/123)  

New feature supporting Jinja2 rendering in `json` and `yaml` deployment config files. 

#### Why
It would be beneficial to be able to define environment variable specific logic within a deployment file, with if statements, for loops and the general functionality that Jinja2 allows. This would enable, for example, the same job deployment configuration file to be reused for different scopes and environments and would improve code reusability.

This functionality would also automatically allow Passing environment variables to the deployment configuration.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by elenamartina** [comment]
> Hi @elenamartina , Sorry for the delayed response. To contribute/review your code in the labs projects (such as dbx) we'll need the signed CLA - please find these details on how to fill it in the `contrib/CONTRIBUTING.md`

Hi @renardeinside, I've been waiting to hear from the legal team at my company and they should approve this anytime now or beginning of next week. Apologies if this is taking long.

**Comment by elenamartina** [comment]
Hi @renardeinside, Gousto has signed the CLA for all members of my team, me included, and it was submitted on Friday. Could you check and let me know if you need anything else for this pr?

**Comment by renardeinside** [comment]
Hi @elenamartina , 
I'll re-iterate internally, but I guess we're good to go - please update your code with the recent changes from the main. 

I also don't see any docs in your PR - do you need help with that? Happy to engage and add docs about this feature.

**Comment by elenamartina** [comment]
Hi @renardeinside, I've updated my branch and reviewed the tests and the docs, which now have some context and two examples (one for Yaml and one for Json).

Please feel free to add more information to the docs that you think could be helpful to users!

**Comment by elenamartina** [comment]
@renardeinside could you kick off the workflow again please? Thank you 🙏🏻

**Comment by elenamartina** [comment]
@renardeinside all done!  👍🏻

**Pull request merged**
