### PR TITLE
add job run logs and notebook output to job launch

### PR DESCRIPTION
**Pull request by justinTM**
## Proposed changes

In addition to existing job run status, add functionality to print out cluster logs and notebook output after launching job.

`--print-output`

https://github.com/databrickslabs/dbx/issues/253

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## PR Status

- [x] Please create a fork of this repository, and a development branch in it. You can name the branch as you would like to, but please make the branch name meaningful.
- [ ] After finishing the development, please run the `make lint` to make sure that code is properly formatted.
- [x] When opening a PR, it's mandatory to reference an issue (or set of issues) it resolves. PRs without linked issues won't be reviewed.
- [ ] Please describe the PR is 4-5 meaningful sentences. These sentences shall answer 3W questions (What is the problem, What is the impact, What is the solution)
- [ ] Please add tests to your PR. PRs which decrease the coverage metric won't be resolved, unless it's a special case of a big refactoring.
- [ ] If you add new functionality, please add some meaningful descriptions to the docs folder.
- [x] All commits shall have a GPG signature verification as per [this documentation](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification).

### CODE REVIEW

**Comment by justinTM** [comment]
hey @matthayes @renardeinside, I am new to MagicMock test framework and I was wondering if you know how I could print the output from `invoke_cli_runner()`? Trying to figure out exactly why exit code is non-zero.

what I have so far:
```python
# test_launch.py
def test_trace_runs(self, *_):
    . . .
    launch_result = invoke_cli_runner(
                        launch, ["--environment", "test", "--job", "sample", "--tags", "cake=cheesecake", "--trace", "--job-output-log-level", "all"]
                    )

    stdout_string = launch_result.stdout_bytes.decode("utf-8")
    print(f"LOG test_trace_runs: {stdout_string}")

    self.assertEqual(launch_result.exit_code, 0)

    expected_strings = [
        "[Run Id: 1] Error - ZeroDivisionError: integer division or modulo by zero",
        "[Run Id: 1] Latest cluster logs - Hello World!",
    ]
    for this_expected_string in expected_strings:
        self.assertTrue(this_expected_string in stdout_string)
```

but the test is failing at the `self.assertEqual(launch_result.exit_code, 0)` and my print statement ` print(f"LOG test_trace_runs: {stdout_string}")` is not showing...

thank you kindly in advance!

**Comment by justinTM** [comment]
```console
================================================================= FAILURES =================================================================
________________________________________________________ LaunchTest.test_trace_runs ________________________________________________________

self = <tests.unit.test_launch.LaunchTest testMethod=test_trace_runs>
_ = (<MagicMock name='get_run_output' id='5047344864'>, <MagicMock name='get_run' id='5045689552'>, <MagicMock name='run_n...ist_jobs' id='5045662144'>, <MagicMock name='list_runs' id='5047442928'>, <MagicMock name='read' id='5047283136'>, ...)
ws_dir = '/Shared/dbx/projects/dev_dbx_74bc22fe', configure_result = <Result okay>, deployment_content = {'test': {'dbfs': {}, 'jobs': []}}

    @patch(
        "databricks_cli.configure.provider.ProfileConfigProvider.get_config",
        return_value=test_dbx_config,
    )
    @patch("databricks_cli.workspace.api.WorkspaceService.mkdirs", return_value=True)
    @patch("mlflow.set_experiment", return_value=None)
    @patch("mlflow.log_artifact", return_value=None)
    @patch("mlflow.set_tags", return_value=None)
    @patch("mlflow.search_runs", return_value=pd.DataFrame([{"run_id": 1, "tags.cake": "cheesecake"}]))
    @patch("databricks_cli.dbfs.api.DbfsService.read", return_value=DEFAULT_DATA_MOCK)
    @patch("databricks_cli.jobs.api.JobsService.list_runs", return_value={"runs": []})
    @patch(
        "databricks_cli.jobs.api.JobsService.list_jobs",
        return_value={
            "jobs": [{"settings": {"name": "sample",},"job_id": 1,}]
        },
    )
    @patch("databricks_cli.jobs.api.JobsService.run_now", return_value={"run_id": "1"})
    @patch(
        "databricks_cli.jobs.api.JobsService.get_run",
        side_effect=[
            {"run_id": "1", "run_page_url": "http://some", "state": {"state_message": "RUNNING", "result_state": None}},
            {"run_id": "1", "run_page_url": "http://some", "state": {"state_message": "RUNNING", "result_state": None}},
            {
                "run_id": "1",
                "run_page_url": "http://some",
                "state": {"state_message": "RUNNING", "life_cycle_state": "TERMINATED", "result_state": "SUCCESS"},
            },
        ],
    )
    @patch(
        "databricks_cli.jobs.api.JobsService.get_run_output",
        side_effect=[
            {
                "notebook_output": {
                    "result": "An arbitrary string passed by calling dbutils.notebook.exit(...)",
                    "truncated": False,
                },
                "logs": "Hello World!",
                "logs_truncated": True,
                "error": "ZeroDivisionError: integer division or modulo by zero",
                "error_trace": "---------------------------------------------------------------------------\nException Traceback (most recent call last)\n 1 numerator = 42\n 2 denominator = 0\n----> 3 return numerator / denominator\n\nZeroDivisionError: integer division or modulo by zero",
                "metadata": {"state": {"life_cycle_state": "PENDING", "result_state": "SUCCESS", "user_cancelled_or_timedout": False, "state_message": ""},}
            },
        ],
    )
    def test_trace_runs(self, *_):
        with self.project_dir:
            ws_dir = "/Shared/dbx/projects/%s" % self.project_name
            configure_result = invoke_cli_runner(
                configure,
                [
                    "--environment",
                    "test",
                    "--profile",
                    self.profile_name,
                    "--workspace-dir",
                    ws_dir,
                ],
            )
            self.assertEqual(configure_result.exit_code, 0)
    
            deployment_content = {"test": {"dbfs": {}, "jobs": []}}
    
            JsonUtils.write(DEFAULT_DEPLOYMENT_FILE_PATH, deployment_content)
    
            def _test():
                deploy_result = invoke_cli_runner(deploy, ["--environment", "test", "--tags", "cake=cheesecake"])
    
                self.assertEqual(deploy_result.exit_code, 0)
    
                launch_result = invoke_cli_runner(
                    launch, ["--environment", "test", "--job", "sample", "--tags", "cake=cheesecake", "--trace"]
                )
    
                self.assertEqual(launch_result.exit_code, 0)
    
                launch_result = invoke_cli_runner(
                    launch, ["--environment", "test", "--job", "sample", "--tags", "cake=cheesecake", "--trace", "--job-output-log-level", "all"]
                )
    
                stdout_string = launch_result.stdout_bytes.decode("utf-8")
                print(f"LOG test_trace_runs: {stdout_string}")
                self.assertEqual(launch_result.exit_code, 0)
    
                expected_strings = [
                    "[Run Id: 1] Error - ZeroDivisionError: integer division or modulo by zero",
                    "[Run Id: 1] Latest cluster logs - Hello World!",
                ]
                # for this_expected_string in expected_strings:
                #     self.assertTrue(this_expected_string in stdout_string)
    
>           self._launch_in_provided_context(_test)

tests/unit/test_launch.py:451: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.pyenv/versions/3.8.13/lib/python3.8/contextlib.py:240: in helper
    return _GeneratorContextManager(func, args, kwds)
../../.pyenv/versions/3.8.13/lib/python3.8/contextlib.py:83: in __init__
    self.gen = func(*args, **kwds)
tests/unit/test_launch.py:47: in _launch_in_provided_context
    test_func()
tests/unit/test_launch.py:430: in _test
    launch_result = invoke_cli_runner(
tests/unit/utils.py:38: in invoke_cli_runner
    raise res.exception
.venv/lib/python3.8/site-packages/click/testing.py:408: in invoke
    return_value = cli.main(args=args or (), prog_name=prog_name, **extra)
.venv/lib/python3.8/site-packages/click/core.py:1055: in main
    rv = self.invoke(ctx)
.venv/lib/python3.8/site-packages/click/core.py:1404: in invoke
    return ctx.invoke(self.callback, **ctx.params)
.venv/lib/python3.8/site-packages/click/core.py:760: in invoke
    return __callback(*args, **kwargs)
dbx/commands/launch.py:264: in launch
    dbx_status = _trace_run(api_client, run_data, job_output_log_level)
dbx/commands/launch.py:513: in _trace_run
    job_output = _wait_run(api_client, run_data, job_output_log_level)
dbx/commands/launch.py:497: in _wait_run
    output.get()
dbx/commands/launch.py:48: in get
    self._response = jobs_service.get_run_output(self.run_data["run_id"])
../../.pyenv/versions/3.8.13/lib/python3.8/unittest/mock.py:1081: in __call__
    return self._mock_call(*args, **kwargs)
../../.pyenv/versions/3.8.13/lib/python3.8/unittest/mock.py:1085: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MagicMock name='get_run_output' id='5047344864'>, args = ('1',), kwargs = {}, effect = <list_iterator object at 0x12cbf1c70>

    def _execute_mock_call(self, /, *args, **kwargs):
        # separate from _increment_mock_call so that awaited functions are
        # executed separately from their call, also AsyncMock overrides this method
    
        effect = self.side_effect
        if effect is not None:
            if _is_exception(effect):
                raise effect
            elif not _callable(effect):
>               result = next(effect)
E               StopIteration

../../.pyenv/versions/3.8.13/lib/python3.8/unittest/mock.py:1142: StopIteration
------------------------------------------------------------ Captured log call -------------------------------------------------------------
INFO     root:utils.py:50 Launching test in directory /var/folders/py/kw209k4d5r19vrhwkf4t_bhm0000gp/T/tmp45_6ddsq with project name dev_dbx_74bc22fe
ERROR    root:utils.py:37 Exception in the cli runner:

---------- coverage: platform darwin, python 3.8.13-final-0 ----------
Name                              Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------
dbx/__init__.py                       1      0      0      0   100%
dbx/api/__init__.py                   0      0      0      0   100%
dbx/api/configure.py                 61      3     18      0    96%
dbx/api/context.py                   13      1      4      1    88%
dbx/commands/__init__.py              0      0      0      0   100%
dbx/commands/configure.py            19      0      0      0   100%
dbx/commands/deploy.py              166     18     56     10    86%
dbx/commands/execute.py             156     25     44     14    78%
dbx/commands/init.py                 31      3     10      3    85%
dbx/commands/launch.py              259     46     80     16    78%
dbx/commands/sync.py                140      0     48      0   100%
dbx/constants.py                      9      0      0      0   100%
dbx/sync/__init__.py                221      0     96      0   100%
dbx/sync/clients.py                 138      0     34      0   100%
dbx/sync/config.py                   28      0      6      0   100%
dbx/sync/constants.py                 2      0      0      0   100%
dbx/sync/event_handler.py            68      0     16      0   100%
dbx/sync/path_matcher.py             50      0     28      0   100%
dbx/sync/snapshot.py                 32      0     16      0   100%
dbx/utils/__init__.py                10      2      0      0    80%
dbx/utils/adjuster.py                72      4     32      2    94%
dbx/utils/common.py                 200     19     70     11    88%
dbx/utils/dependency_manager.py      51      3     20      2    93%
dbx/utils/file_uploader.py           27      0      6      0   100%
dbx/utils/job_listing.py             13      1      6      1    89%
dbx/utils/json.py                    11      0      2      0   100%
dbx/utils/named_properties.py        89     26     46      3    68%
dbx/utils/options.py                  6      0      0      0   100%
dbx/utils/policy_parser.py           34      3     22      5    86%
dbx/utils/v1_client.py               27     12      2      0    59%
-------------------------------------------------------------------
TOTAL                              1934    166    662     68    90%

========================================================= short test summary info ==========================================================
FAILED tests/unit/test_launch.py::LaunchTest::test_trace_runs - StopIteration
================================================= 1 failed, 190 passed in 87.17s (0:01:27) =================================================
make: *** [test] Error 1
```

**Comment by renardeinside** [comment]
hi @justinTM , 
I'm currently working heavily on refactoring the tests, I'll update you in 2-3 days with a proper testing API.

**Comment by justinTM** [comment]
@renardeinside sweet thank you!

I'll work with the built wheel of my fork in the meantime

**Comment by justinTM** [comment]
i'm still using the fork since there are more features than in main. i need to see output periodically instead of just at job completion. i also plan to add worker stderr to the output. 

will reconcile the differences between main and fork later

**Comment by renardeinside** [comment]
ah, I get it now 😄 
 
please feel free to continue working on the branch then, and feel free to re-open the PR when it's ready for review.

**Comment by renardeinside** [comment]
regarding your question above (how to capture standard output) - take a look at the new tests for `--include-output`, they're using `capsys` fixture to verify the content

**Pull request closed without merging**
