### PR TITLE
Refactor unit test

### PR DESCRIPTION
**Pull request by copdips**
## Proposed changes

1. Refactor `unit test` folder layout in order to reflect the dbx source folder layout as much as possible. There's no change in the test files content except for a tiny import issue that I should replace `from .conftest` by `from tests.unit.conftest`. 
   BTW the folder `tests/unit/sync` is not refactored, because  it's a little bit tricky.
2. In `Makefile`, run pytest in parallel.
3. In `Makefile`, add ternary on var `VENV_NAME`, as many developers use also `venv` as venv name.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

Please find below a diff on the tests/unit folder layout:

**Before this PR:**

```bash
tests/unit/
├── __init__.py
├── conftest.py
├── sync
│   ├── __init__.py
│   ├── clients
│   │   ├── conftest.py
│   │   ├── test_dbfs_client.py
│   │   ├── test_get_user.py
│   │   └── test_repos_client.py
│   ├── sync
│   │   ├── __init__.py
│   │   ├── test_dry_run.py
│   │   ├── test_filtering.py
│   │   ├── test_full_sync.py
│   │   ├── test_many_files.py
│   │   ├── test_sync.py
│   │   └── test_unmatched_deletes.py
│   ├── test_commands.py
│   ├── test_config.py
│   ├── test_event_handler.py
│   ├── test_main_loop.py
│   ├── test_path_matcher.py
│   ├── test_snapshot.py
│   └── utils.py
├── test_auth.py
├── test_common.py
├── test_configure.py
├── test_context.py
├── test_datafactory.py
├── test_dependency_manager.py
├── test_deploy.py
├── test_execute.py
├── test_file_uploader.py
├── test_jinja_vars_file.py
├── test_launch.py
├── test_named_properties.py
├── test_output_provider.py
└── test_policy_parser.py
```

**After this PR:**

```bash
tests/unit/
├── __init__.py
├── api
│   ├── __init__.py
│   ├── test_auth.py
│   ├── test_context.py
│   └── test_output_provider.py
├── commands
│   ├── __init__.py
│   ├── test_configure.py
│   ├── test_datafactory.py
│   ├── test_deploy.py
│   ├── test_deploy_jinja_variables_file.py
│   ├── test_execute.py
│   └── test_launch.py
├── conftest.py
├── sync
│   ├── __init__.py
│   ├── clients
│   │   ├── conftest.py
│   │   ├── test_dbfs_client.py
│   │   ├── test_get_user.py
│   │   └── test_repos_client.py
│   ├── sync
│   │   ├── __init__.py
│   │   ├── test_dry_run.py
│   │   ├── test_filtering.py
│   │   ├── test_full_sync.py
│   │   ├── test_many_files.py
│   │   ├── test_sync.py
│   │   └── test_unmatched_deletes.py
│   ├── test_commands.py
│   ├── test_config.py
│   ├── test_event_handler.py
│   ├── test_main_loop.py
│   ├── test_path_matcher.py
│   ├── test_snapshot.py
│   └── utils.py
└── utils
    ├── __init__.py
    ├── test_common.py
    ├── test_dependency_manager.py
    ├── test_file_uploader.py
    ├── test_named_properties.py
    └── test_policy_parser.py
```

### CODE REVIEW

**Comment by copdips** [comment]
@renardeinside 
could you please approve the running of the ci workflows ?

**Comment by renardeinside** [comment]
hi @copdips , 
please sign your commits. Unsigned commits cannot be merged.

**Comment by copdips** [comment]
> hi @copdips , please sign your commits. Unsigned commits cannot be merged.

@renardeinside ,
Thx, they're signed now.

**Comment by renardeinside** [comment]
LGTM, great job @copdips !

**Pull request merged**
