### PR TITLE
Support includes in jinja2 templates

### PR DESCRIPTION
**Pull request by skylarbpayne**
## Proposed changes
Prior to this change, the jinja2 `include` directive only allows inclusion of files that are "below" the parent directory of the template file; e.g. if you use `/path/to/my_template.json.j2` then only templates in a path with prefix `/path/to` can be included. This restricts ability to organize files within a repo and use `include` as an abstraction.

This change sets the root directory as the jinja2 rendering environment. This allows templates to include other files from the directory (rather than being limited to only the parent directory of the specified template).

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

Briefly discussed in #191 .

Added test initially fails with:

```
FAILED tests/unit/test_common.py::CommonUnitTest::test_jinja_with_include - jinja2.exceptions.TemplateNotFound: tests/deployment-configs/includes/cluster-test.json.j2
```

and succeeds after the slight implementation changes in this PR.

Note: at a first look, it may be desirable to add a similar test for inclusions with yaml-based templates. However, because yaml is indent-sensitive, and jinja2 includes do not satisfy any constraints of indentation, I wasn't sure of what a realistic use case was for this (i.e. the yaml version of the test I have would not produce valid yaml from jinja2 rendering).

### CODE REVIEW

**Comment by skylarbpayne** [comment]
@renardeinside LMK if there's anything additional I need to do here :)

**Comment by skylarbpayne** [comment]
@renardeinside -- It's been almost a month, understand if busy but a little communication would go a long way :)

**Comment by renardeinside** [comment]
hey @skylarbpayne , codecov is too harsh, I'm still able to merge the PR so this isn't an issue. 
However, would be great if you'll reflect on the changes you've done to the CHANGELOG.md (currently we still collect this file manually, unfortunately).

**Comment by skylarbpayne** [comment]
> hey @skylarbpayne , codecov is too harsh, I'm still able to merge the PR so this isn't an issue. However, would be great if you'll reflect on the changes you've done to the CHANGELOG.md (currently we still collect this file manually, unfortunately).

No problem -- just added a new line to CHANGELOG :)

**Comment by renardeinside** [comment]
thanks a lot @skylarbpayne, you did a great job!

**Pull request merged**
