### PR TITLE
✨ support for files bigger than 1MB in sync

### PR DESCRIPTION
**Pull request by greentim**
## Proposed changes

Bug report: https://github.com/databrickslabs/dbx/issues/508
The rest API for put only works for files 1MB or less.  There is a separate api to call for larger files, that requires three or more calls: 1 to create the request, 1 or more add-block calls to upload 1MB chunks , and finally a close.  This PR will use put if the file length is < 1MB, and otherwise uses the create/add/close apis.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

It was necessary to switch to using AsyncMock in the tests to properly mock the calls with the change to await the result of the api call, which is necessary to get the handle for the block uploads.  test_delete_secure was duplicated in main and so one was removed.  We have been using this patch in my company since June 2022 with no issues.

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @greentim , 
thanks a lot for your PR! Please sign your commits, we don't approve any unsigned commits due to security reasons.

**Comment by greentim** [comment]
Hello, the commit is now verified.  There was a mismatch between my committer email and my github verified email addresses.
Thanks,Tim

    On Wednesday, October 12, 2022 at 06:02:16 AM CDT, Ivan Trusov ***@***.***> wrote:  
 
 


hi @greentim ,
thanks a lot for your PR! Please sign your commits, we don't approve any unsigned commits due to security reasons.

**Comment by renardeinside** [comment]
@matthayes please review this PR

**Comment by renardeinside** [comment]
hi @greentim , 
could you please resolve the conflict above? I'll take a look at this PR myself and merge it for 0.8.7

**Comment by jeremy010203** [comment]
Hello @renardeinside,
I performed the merge myself [https://github.com/jeremy010203/dbx/tree/greentim-bug/dbfs_sync_1mb](https://github.com/jeremy010203/dbx/tree/greentim-bug/dbfs_sync_1mb) since it is a feature that I need and the creator of the PR seems inactive.
I am not familiar with the process do I have to open a new PR? Thanks

**Comment by greentim** [comment]
hello @renardeinside, @jeremy010203 Sorry I missed the previous message for some reason.  I have resolved conflicts and I believe this should be ready for review again.

**Comment by jeremy010203** [comment]
@matthayes is it possible to have a look to that PR please?
It will be very useful for our team to migrate to Databricks using dbx!
Thanks a lot 😃

**Review by matthayes — APPROVED** [review]
Sorry for the delayed review.  I ran a test and this appears to work.  I synced a large file, then fetched it, then ran a diff, and the contents matched.  Thanks for the fix!

**Comment by matthayes** [comment]
Please fix the failing unit test.  Otherwise this looks good to me.

**Comment by matthayes** [comment]
Here's the fix:

```
diff --git a/tests/unit/sync/clients/test_dbfs_client.py b/tests/unit/sync/clients/test_dbfs_client.py
index d2f2190..e983390 100644
--- a/tests/unit/sync/clients/test_dbfs_client.py
+++ b/tests/unit/sync/clients/test_dbfs_client.py
@@ -240,11 +240,11 @@ def test_put_max_block_size_exceeded(client: DBFSClient, dummy_file_path_2mb: st
     def mock_post(url, *args, **kwargs):
         resp = AsyncMock()
         setattr(type(resp), "status", PropertyMock(return_value=200))
-        if "/base/api/2.0/dbfs/put" in url:
+        if "/api/2.0/dbfs/put" in url:
             contents = kwargs.get("json").get("contents")
             if len(contents) > 1024 * 1024:  # replicate the api error thrown when contents exceeds max allowed
                 setattr(type(resp), "status", PropertyMock(return_value=400))
-        elif "/base/api/2.0/dbfs/create" in url:
+        elif "/api/2.0/dbfs/create" in url:
             # return a mock response json
             resp.json = MagicMock(side_effect=mock_json)
 
@@ -262,11 +262,11 @@ def test_put_max_block_size_exceeded(client: DBFSClient, dummy_file_path_2mb: st
     chunks = textwrap.wrap(base64.b64encode(bytes(expected_contents, encoding="utf8")).decode("ascii"), 1024 * 1024)
 
     assert session.post.call_count == len(chunks) + 2
-    assert session.post.call_args_list[0][1]["url"] == "http://fakehost.asdf/base/api/2.0/dbfs/create"
-    assert session.post.call_args_list[1][1]["url"] == "http://fakehost.asdf/base/api/2.0/dbfs/add-block"
-    assert session.post.call_args_list[2][1]["url"] == "http://fakehost.asdf/base/api/2.0/dbfs/add-block"
-    assert session.post.call_args_list[3][1]["url"] == "http://fakehost.asdf/base/api/2.0/dbfs/add-block"
-    assert session.post.call_args_list[4][1]["url"] == "http://fakehost.asdf/base/api/2.0/dbfs/close"
+    assert session.post.call_args_list[0][1]["url"] == "http://fakehost.asdf/api/2.0/dbfs/create"
+    assert session.post.call_args_list[1][1]["url"] == "http://fakehost.asdf/api/2.0/dbfs/add-block"
+    assert session.post.call_args_list[2][1]["url"] == "http://fakehost.asdf/api/2.0/dbfs/add-block"
+    assert session.post.call_args_list[3][1]["url"] == "http://fakehost.asdf/api/2.0/dbfs/add-block"
+    assert session.post.call_args_list[4][1]["url"] == "http://fakehost.asdf/api/2.0/dbfs/close"
```

**Pull request merged**
