### PR TITLE
Sai/changelog updates

### PR DESCRIPTION
**Pull request by jspreddy**
## Proposed changes

General updates for ease of contribution.
- .editorconfig
- Changelog updates based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
- Dev env makefile option for pyenv users.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jspreddy** [comment]
@renardeinside can you please review this. I would like to get this in before I pickup the yaml config feature.

**Comment by renardeinside** [comment]
hi @jspreddy 
please sign your commits as per this [doc](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification). 
everything else looks good to me.

**Comment by jspreddy** [comment]
Signed.

**Comment by renardeinside** [comment]
thanks a lot @jspreddy , LGTM

**Pull request merged**
