### PR TITLE
Uses python:3.8-bullseye for GitLab CI stages.

### LINKED ISSUE #647: python-3.8-stretch docker image does not exist in python_basic template with gitlab cicd.
## Expected Behavior

The following command sets up the `python_basic` template with a `.gitlab-ci.yml`

```bash
dbx init --template=python_basic \
    -p "cicd_tool=Gitlab" \ 
    ....
```

I would expect that the Gitlab CI/CD runs.

## Current Behavior

```
WARNING: Failed to pull image with policy "always": Error response from daemon: manifest for python:3.8-stretch not found: manifest unknown: manifest unknown (manager.go:237:1s)
ERROR: Job failed: failed to pull image "python:3.8-stretch" with specified policies [always]: Error response from daemon: manifest for python:3.8-stretch not found: manifest unknown: manifest unknown (manager.go:237:1s)
```

A search on Docker Hub shows, that this tag does not exist: https://hub.docker.com/_/python/tags?page=1&name=stretch

## Context

I used and tested `python:3.8-bullseye` in all stages of https://github.com/databrickslabs/dbx/blob/main/dbx/templates/projects/python_basic/components/.gitlab-ci.yml which worked nicely.

## Your Environment

* dbx version used: [dbx][2022-12-22 10:34:49.730] 🧱 Databricks eXtensions aka dbx, version ~> 0.8.7
* GitLab Community Edition [15.6.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v15.6.2)
* Databricks Runtime version:

### PR DESCRIPTION
**Pull request by j-4**
## Proposed changes

Closes #647 "python-3.8-stretch docker image does not exist in python_basic template with gitlab cicd."
by using `python:3.8-bullseye` docker image for all stages.

## Types of changes

What types of changes does your code introduce to dbx?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by renardeinside** [comment]
hi @j-4 
thanks for contributing! could you please reflect the changes in the CHANGELOG as required?

**Comment by renardeinside** [comment]
Also, all commits should be signed. We don't accept unsigned commits for security reasons.

**Comment by j-4** [comment]
Hi @renardeinside,

thanks for your review. I made the requested changes and hope that it satisfy the requirements now :)

**Comment by renardeinside** [comment]
hi @j-4 , 
happy to merge your PRs, but first - could you please check if you've done the steps described [here](https://github.com/databrickslabs/dbx/blob/main/contrib/CONTRIBUTING.md), specifically the CLA part?

**Comment by renardeinside** [comment]
hey @j-4 , to close the loop on this one - please use Databricks Asset Bundles instead of dbx.
If you still use dbx, please use a custom template.

**Pull request closed without merging**
